export const GET_PRODUCT_REQ ="GET_PRODUCT_REQ";
export const GET_PRODUCT_SUCESS ="GET_PRODUCT_SUCESS";
export const GET_PRODUCT_FAILURE ="GET_PRODUCT_FAILURE";
export const GET_PRODUCT_DATA ="GET_PRODUCT_DATA";
export const SORT_DATA = "SORT_DATA";

export const GET_CLICKED_DATA_REQ = "GET_CLICKED_DATA_REQ";
export const GET_CLICKED_DATA_SUCCESS = "GET_CLICKED_DATA_SUCCESS";
export const GET_CLICKED_DATA_FAILURE = "GET_CLICKED_DATA_FAILURE";
